// shorted class name - less bytes needs to send as custom stat
Class AchMaps extends ScrnMapAchievements;

#exec OBJ LOAD FILE=ScrnAch_T.utx

defaultproperties
{
     ProgressName="Map Achievements"

     AchDefs(0)=(id="KF-WestLondon",DisplayName="Pub Crawl",Description="West London",Icon=Texture'KillingFloorHUD.Achievements.Achievement_0')
     AchDefs(1)=(id="KF-WestLondonHard",DisplayName="Hard Pub Crawl",Description="West London",Icon=Texture'KillingFloorHUD.Achievements.Achievement_6')
     AchDefs(2)=(id="KF-WestLondonSui",DisplayName="Suicidal Pub Crawl",Description="West London",Icon=Texture'KillingFloorHUD.Achievements.Achievement_12')
     AchDefs(3)=(id="KF-WestLondonHoe",DisplayName="Hellish Pub Crawl",Description="West London",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_65')
     AchDefs(4)=(id="KF-Manor",DisplayName="Lord of the Manor",Description="Manor",Icon=Texture'KillingFloorHUD.Achievements.Achievement_1')
     AchDefs(5)=(id="KF-ManorHard",DisplayName="Duke of the Manor",Description="Manor",Icon=Texture'KillingFloorHUD.Achievements.Achievement_7')
     AchDefs(6)=(id="KF-ManorSui",DisplayName="Emperor of the Manor",Description="Manor",Icon=Texture'KillingFloorHUD.Achievements.Achievement_13')
     AchDefs(7)=(id="KF-ManorHoe",DisplayName="Demonic King of the Manor",Description="Manor",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_66')
     AchDefs(8)=(id="KF-Farm",DisplayName="Chicken Farmer",Description="Farm",Icon=Texture'KillingFloorHUD.Achievements.Achievement_2')
     AchDefs(9)=(id="KF-FarmHard",DisplayName="Cattle Farmer",Description="Farm",Icon=Texture'KillingFloorHUD.Achievements.Achievement_8')
     AchDefs(10)=(id="KF-FarmSui",DisplayName="Alligator Farmer",Description="Farm",Icon=Texture'KillingFloorHUD.Achievements.Achievement_14')
     AchDefs(11)=(id="KF-FarmHoe",DisplayName="Demon Farmer",Description="Farm",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_67')
     AchDefs(12)=(id="KF-Offices",DisplayName="The Boss",Description="Offices",Icon=Texture'KillingFloorHUD.Achievements.Achievement_3')
     AchDefs(13)=(id="KF-OfficesHard",DisplayName="Hard Boss",Description="Offices",Icon=Texture'KillingFloorHUD.Achievements.Achievement_9')
     AchDefs(14)=(id="KF-OfficesSui",DisplayName="Mad Boss",Description="Offices",Icon=Texture'KillingFloorHUD.Achievements.Achievement_15')
     AchDefs(15)=(id="KF-OfficesHoe",DisplayName="Boss from Hell",Description="Offices",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_68')
     AchDefs(16)=(id="KF-BioticsLab",DisplayName="Lab Cleaner",Description="Biotics Lab",Icon=Texture'KillingFloorHUD.Achievements.Achievement_4')
     AchDefs(17)=(id="KF-BioticsLabHard",DisplayName="Lab Assistant",Description="Biotics Lab",Icon=Texture'KillingFloorHUD.Achievements.Achievement_10')
     AchDefs(18)=(id="KF-BioticsLabSui",DisplayName="Lab Professor",Description="Biotics Lab",Icon=Texture'KillingFloorHUD.Achievements.Achievement_16')
     AchDefs(19)=(id="KF-BioticsLabHoe",DisplayName="Scientist from Hell",Description="Biotics Lab",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_69')
     AchDefs(20)=(id="KF-Foundry",DisplayName="Tin Man",Description="Foundry",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_44')
     AchDefs(21)=(id="KF-FoundryHard",DisplayName="Steel Worker",Description="Foundry",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_45')
     AchDefs(22)=(id="KF-FoundrySui",DisplayName="Man of Steel",Description="Foundry",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_46')
     AchDefs(23)=(id="KF-FoundryHoe",DisplayName="Diablo Steel Man",Description="Foundry",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_70')
     AchDefs(24)=(id="KF-Bedlam",DisplayName="A Bit Barmy",Description="Bedlam",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_47')
     AchDefs(25)=(id="KF-BedlamHard",DisplayName="Gone Mental",Description="Bedlam",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_48')
     AchDefs(26)=(id="KF-BedlamSui",DisplayName="Complete Barking",Description="Bedlam",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_49')
     AchDefs(27)=(id="KF-BedlamHoe",DisplayName="Commit-ed for life",Description="Bedlam",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_71')
     AchDefs(28)=(id="KF-Wyre",DisplayName="Squirrel King of the Dark Forest",Description="Wyre",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_50')
     AchDefs(29)=(id="KF-WyreHard",DisplayName="Raccoon King of the Dark Forest",Description="Wyre",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_51')
     AchDefs(30)=(id="KF-WyreSui",DisplayName="Bear King of the Dark Forest",Description="Wyre",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_52')
     AchDefs(31)=(id="KF-WyreHoe",DisplayName="Wolf King of the Dark Forest",Description="Wyre",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_72')
     AchDefs(32)=(id="KF-Biohazard",DisplayName="Waste Disposal",Description="Biohazard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_73')
     AchDefs(33)=(id="KF-BiohazardHard",DisplayName="Waste Land",Description="Biohazard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_74')
     AchDefs(34)=(id="KF-BiohazardSui",DisplayName="Waste of Space",Description="Biohazard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_75')
     AchDefs(35)=(id="KF-BiohazardHoe",DisplayName="Wasted",Description="Biohazard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_76')
     AchDefs(36)=(id="KF-Crash",DisplayName="Warehouse Janitor",Description="Crash",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_77')
     AchDefs(37)=(id="KF-CrashHard",DisplayName="Warehouse Forklift Operator",Description="Crash",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_78')
     AchDefs(38)=(id="KF-CrashSui",DisplayName="Warehouse Foreman",Description="Crash",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_79')
     AchDefs(39)=(id="KF-CrashHoe",DisplayName="Warehouse Manager",Description="Crash",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_80')
     AchDefs(40)=(id="KF-Departed",DisplayName="Departure Gallery",Description="Departed",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_81')
     AchDefs(41)=(id="KF-DepartedHard",DisplayName="Departure Lounge",Description="Departed",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_82')
     AchDefs(42)=(id="KF-DepartedSui",DisplayName="Departure Gate",Description="Departed",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_83')
     AchDefs(43)=(id="KF-DepartedHoe",DisplayName="Dear Departed",Description="Departed",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_84')
     AchDefs(44)=(id="KF-FilthsCross",DisplayName="Running Late",Description="Filths Cross",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_85')
     AchDefs(45)=(id="KF-FilthsCrossHard",DisplayName="Missed Connection",Description="Filths Cross",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_86')
     AchDefs(46)=(id="KF-FilthsCrossSui",DisplayName="Train Wreck",Description="Filths Cross",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_87')
     AchDefs(47)=(id="KF-FilthsCrossHoe",DisplayName="Pile Up",Description="Filths Cross",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_88')
     AchDefs(48)=(id="KF-HospitalHorrors",DisplayName="Gimme a Plaster!",Description="Hospital Horrors",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_89')
     AchDefs(49)=(id="KF-HospitalHorrorsHard",DisplayName="That Bloody Well Hurts!",Description="Hospital Horrors",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_90')
     AchDefs(50)=(id="KF-HospitalHorrorsSui",DisplayName="I'm Dying Here!",Description="Hospital Horrors",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_91')
     AchDefs(51)=(id="KF-HospitalHorrorsHoe",DisplayName="Not Dead Yet!",Description="Hospital Horrors",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_92')
     AchDefs(52)=(id="KF-Icebreaker",DisplayName="Ice Cube",Description="Icebreaker",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_93')
     AchDefs(53)=(id="KF-IcebreakerHard",DisplayName="Crushed Ice",Description="Icebreaker",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_94')
     AchDefs(54)=(id="KF-IcebreakerSui",DisplayName="Iceberg",Description="Icebreaker",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_95')
     AchDefs(55)=(id="KF-IcebreakerHoe",DisplayName="Comet",Description="Icebreaker",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_96')
     AchDefs(56)=(id="KF-MountainPass",DisplayName="Daytrip",Description="Mountain Pass",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_97')
     AchDefs(57)=(id="KF-MountainPassHard",DisplayName="Gone Camping",Description="Mountain Pass",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_98')
     AchDefs(58)=(id="KF-MountainPassSui",DisplayName="Mountaineer",Description="Mountain Pass",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_99')
     AchDefs(59)=(id="KF-MountainPassHoe",DisplayName="Park Ranger",Description="Mountain Pass",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_100')
     AchDefs(60)=(id="KF-Suburbia",DisplayName="Park Ranger",Description="Suburbia",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_101')
     AchDefs(61)=(id="KF-SuburbiaHard",DisplayName="Private Security",Description="Suburbia",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_102')
     AchDefs(62)=(id="KF-SuburbiaSui",DisplayName="Vigilante",Description="Suburbia",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_103')
     AchDefs(63)=(id="KF-SuburbiaHoe",DisplayName="SWAT",Description="Suburbia",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_104')
     AchDefs(64)=(id="KF-Waterworks",DisplayName="Slight Drip",Description="Waterworks",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_105')
     AchDefs(65)=(id="KF-WaterworksHard",DisplayName="Burst Pipe",Description="Waterworks",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_106')
     AchDefs(66)=(id="KF-WaterworksSui",DisplayName="Pressure Failure",Description="Waterworks",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_107')
     AchDefs(67)=(id="KF-WaterworksHoe",DisplayName="Floodgate to Hell",Description="Waterworks",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_108')
     AchDefs(68)=(id="KF-EvilSantasLair",DisplayName="Walking in A Winter Horror Land",Description="EvilSantasLair",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_114')
     AchDefs(69)=(id="KF-EvilSantasLairHard",DisplayName="Silent Night, Evil Night",Description="EvilSantasLair",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_115')
     AchDefs(70)=(id="KF-EvilSantasLairSui",DisplayName="I'm Dreaming of a Red Christmas",Description="EvilSantasLair",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_116')
     AchDefs(71)=(id="KF-EvilSantasLairHoe",DisplayName="Grandma got Eaten by a Reindeer",Description="EvilSantasLair",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_117')
     AchDefs(72)=(id="KF-Aperture",DisplayName="Science Got Done",Description="Aperture",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_133')
     AchDefs(73)=(id="KF-ApertureHard",DisplayName="Still Alive",Description="Aperture",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_134')
     AchDefs(74)=(id="KF-ApertureSui",DisplayName="This is a Triumph",Description="Aperture",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_135')
     AchDefs(75)=(id="KF-ApertureHoe",DisplayName="I'm Making a Note Here, Huge Success",Description="Aperture",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_136')
     AchDefs(76)=(id="KF-AbusementPark",DisplayName="Flea Circus",Description="Abusement Park",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_138')
     AchDefs(77)=(id="KF-AbusementParkHard",DisplayName="Dog and Pony Show",Description="Abusement Park",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_139')
     AchDefs(78)=(id="KF-AbusementParkSui",DisplayName="3 Ring Circus",Description="Abusement Park",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_140')
     AchDefs(79)=(id="KF-AbusementParkHoe",DisplayName="On Top of the Big Top",Description="Abusement Park",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_141')
     AchDefs(80)=(id="KF-IceCave",DisplayName="Snow Cone",Description="Ice Cave",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_171')
     AchDefs(81)=(id="KF-IceCaveHard",DisplayName="Stay Frosty",Description="Ice Cave",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_172')
     AchDefs(82)=(id="KF-IceCaveSui",DisplayName="On the Rocks",Description="Ice Cave",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_173')
     AchDefs(83)=(id="KF-IceCaveHoe",DisplayName="Anti Freeze",Description="Ice Cave",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_174')
     AchDefs(84)=(id="KF-Hellride",DisplayName="Highway to Heaven",Description="Hellride",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_181')
     AchDefs(85)=(id="KF-HellrideHard",DisplayName="Stuck in Limbo",Description="Hellride",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_182')
     AchDefs(86)=(id="KF-HellrideSui",DisplayName="Demonic Road",Description="Hellride",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_183')
     AchDefs(87)=(id="KF-HellrideHoe",DisplayName="Devil's Co-pilot",Description="Hellride",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_184')
     AchDefs(88)=(id="KF-HillbillyHorror",DisplayName="Third Cousins",Description="Hillbilly Horror",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_97')
     AchDefs(89)=(id="KF-HillbillyHorrorHard",DisplayName="Second Cousins",Description="Hillbilly Horror",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_98')
     AchDefs(90)=(id="KF-HillbillyHorrorSui",DisplayName="First Cousins",Description="Hillbilly Horror",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_99')
     AchDefs(91)=(id="KF-HillbillyHorrorHoe",DisplayName="Zeroth Cousins",Description="Hillbilly Horror",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_100')
     AchDefs(92)=(id="KF-MoonBase",DisplayName="Here is to us",Description="Moon Base",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_204')
     AchDefs(93)=(id="KF-MoonBaseHard",DisplayName="Attempting Re-entry",Description="Moon Base",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_205')
     AchDefs(94)=(id="KF-MoonBaseSui",DisplayName="Amusing Death",Description="Moon Base",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_206')
     AchDefs(95)=(id="KF-MoonBaseHoe",DisplayName="One Giant Leap (Back) for Mankind",Description="Moon Base",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_207')


     AchDefs(96)=(id="KF-Aventine",DisplayName="Lord of Aventive",Description="Aventine",Icon=Texture'ScrnAch_T.Maps.Aventine_0')
     AchDefs(97)=(id="KF-AventineHard",DisplayName="Duke of Aventine",Description="Aventine",Icon=Texture'ScrnAch_T.Maps.Aventine_1')
     AchDefs(98)=(id="KF-AventineSui",DisplayName="Emperor of Aventine",Description="Aventine",Icon=Texture'ScrnAch_T.Maps.Aventine_2')
     AchDefs(99)=(id="KF-AventineHoE",DisplayName="Demonic King of Aventine",Description="Aventine",Icon=Texture'ScrnAch_T.Maps.Aventine_3')

     AchDefs(100)=(id="KF-Constriction",DisplayName="Rats in the Wall",Description="Constriction",Icon=Texture'ScrnAch_T.Maps.Constriction_0')
     AchDefs(101)=(id="KF-ConstrictionHard",DisplayName="Barking Dogs Outside",Description="Constriction",Icon=Texture'ScrnAch_T.Maps.Constriction_1')
     AchDefs(102)=(id="KF-ConstrictionSui",DisplayName="Screaming Maidens",Description="Constriction",Icon=Texture'ScrnAch_T.Maps.Constriction_2')
     AchDefs(103)=(id="KF-ConstrictionHoE",DisplayName="...and the Crazed Lord of the Manor died - again",Description="Constriction",Icon=Texture'ScrnAch_T.Maps.Constriction_3')

     AchDefs(104)=(id="KF-CornerMarket_v3",DisplayName="Barrow Boy",Description="Corner Market",Icon=Texture'ScrnAch_T.Maps.CornerMarket_0')
     AchDefs(105)=(id="KF-CornerMarket_v3Hard",DisplayName="Supermarket Manager",Description="Corner Market",Icon=Texture'ScrnAch_T.Maps.CornerMarket_1')
     AchDefs(106)=(id="KF-CornerMarket_v3Sui",DisplayName="BestBuy's Director",Description="Corner Market",Icon=Texture'ScrnAch_T.Maps.CornerMarket_2')
     AchDefs(107)=(id="KF-CornerMarket_v3HoE",DisplayName="HellBuy's Director",Description="Corner Market",Icon=Texture'ScrnAch_T.Maps.CornerMarket_3')

     AchDefs(108)=(id="KF-Corruption",DisplayName="Bug in the System",Description="Corruption",Icon=Texture'ScrnAch_T.Maps.Corruption_0')
     AchDefs(109)=(id="KF-CorruptionHard",DisplayName="Infected System",Description="Corruption",Icon=Texture'ScrnAch_T.Maps.Corruption_1')
     AchDefs(110)=(id="KF-CorruptionSui",DisplayName="Critical System Failure",Description="Corruption",Icon=Texture'ScrnAch_T.Maps.Corruption_2')
     AchDefs(111)=(id="KF-CorruptionHoE",DisplayName="The Blue Screen",Description="Corruption",Icon=Texture'ScrnAch_T.Maps.Corruption_3')

     AchDefs(112)=(id="KF-HarbourV3",DisplayName="Sailor",Description="Harbour",Icon=Texture'ScrnAch_T.Maps.Harbour_0')
     AchDefs(113)=(id="KF-HarbourV3Hard",DisplayName="Boatswain",Description="Harbour",Icon=Texture'ScrnAch_T.Maps.Harbour_1')
     AchDefs(114)=(id="KF-HarbourV3Sui",DisplayName="Maritime Pilot",Description="Harbour",Icon=Texture'ScrnAch_T.Maps.Harbour_2')
     AchDefs(115)=(id="KF-HarbourV3HoE",DisplayName="Demonic Captain",Description="Harbour",Icon=Texture'ScrnAch_T.Maps.Harbour_3')

     AchDefs(116)=(id="Kf-Hell",DisplayName="Imp",Description="Hell",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_243')
     AchDefs(117)=(id="Kf-HellHard",DisplayName="Mancubus",Description="Hell",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_244')
     AchDefs(118)=(id="Kf-HellSui",DisplayName="Hell Knight",Description="Hell",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_245')
     AchDefs(119)=(id="Kf-HellHoE",DisplayName="Cyberdemon",Description="Hell",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_246')

     AchDefs(120)=(id="KF-HellGate",DisplayName="Knock, knock. Who's there?",Description="Hell Gate",Icon=Texture'ScrnAch_T.Maps.HellGate_0')
     AchDefs(121)=(id="KF-HellGateHard",DisplayName="Gate Keeper",Description="Hell Gate",Icon=Texture'ScrnAch_T.Maps.HellGate_1')
     AchDefs(122)=(id="KF-HellGateSui",DisplayName="Free Sauna Inside",Description="Hell Gate",Icon=Texture'ScrnAch_T.Maps.HellGate_2')
     AchDefs(123)=(id="KF-HellGateHoE",DisplayName="Open up! It's me - Satan.",Description="Hell Gate",Icon=Texture'ScrnAch_T.Maps.HellGate_3')

     AchDefs(124)=(id="KF-OldCity",DisplayName="Survivor of the Deserted City",Description="Old City",Icon=Texture'ScrnAch_T.Maps.OldCity_0')
     AchDefs(125)=(id="KF-OldCityHard",DisplayName="Survivor of the Lost City",Description="Old City",Icon=Texture'ScrnAch_T.Maps.OldCity_1')
     AchDefs(126)=(id="KF-OldCitySui",DisplayName="Survivor of the Dead City",Description="Old City",Icon=Texture'ScrnAch_T.Maps.OldCity_2')
     AchDefs(127)=(id="KF-OldCityHoE",DisplayName="Survivor of the UnDead City",Description="Old City",Icon=Texture'ScrnAch_T.Maps.OldCity_3')

     AchDefs(128)=(id="KF-SilentHill",DisplayName="Silent Hill",Description="Silent Hill",Icon=Texture'ScrnAch_T.Maps.SilentHill_0')
     AchDefs(129)=(id="KF-SilentHillHard",DisplayName="Hard Hill",Description="Silent Hill",Icon=Texture'ScrnAch_T.Maps.SilentHill_1')
     AchDefs(130)=(id="KF-SilentHillSui",DisplayName="Suicidal Hill",Description="Silent Hill",Icon=Texture'ScrnAch_T.Maps.SilentHill_2')
     AchDefs(131)=(id="KF-SilentHillHoE",DisplayName="Otherworld",Description="Silent Hill",Icon=Texture'ScrnAch_T.Maps.SilentHill_3')

     AchDefs(132)=(id="KF-SunnyLandSanitarium",DisplayName="Hallucinations",Description="Sunny Land Sanitarium",Icon=Texture'ScrnAch_T.Maps.SunnyLandSanitarium_0')
     AchDefs(133)=(id="KF-SunnyLandSanitariumHard",DisplayName="Delirium Tremens",Description="Sunny Land Sanitarium",Icon=Texture'ScrnAch_T.Maps.SunnyLandSanitarium_1')
     AchDefs(134)=(id="KF-SunnyLandSanitariumSui",DisplayName="Schizophrenia",Description="Sunny Land Sanitarium",Icon=Texture'ScrnAch_T.Maps.SunnyLandSanitarium_2')
     AchDefs(135)=(id="KF-SunnyLandSanitariumHoE",DisplayName="Diabolical Obsession",Description="Sunny Land Sanitarium",Icon=Texture'ScrnAch_T.Maps.SunnyLandSanitarium_3')

     AchDefs(136)=(id="KF-Swamp",DisplayName="This is My Swamp!",Description="Swamp",Icon=Texture'ScrnAch_T.Maps.Swamp_0')
     AchDefs(137)=(id="KF-SwampHard",DisplayName="Give Me Back My Swamp!",Description="Swamp",Icon=Texture'ScrnAch_T.Maps.Swamp_1')
     AchDefs(138)=(id="KF-SwampSui",DisplayName="I'll Die For My Swamp",Description="Swamp",Icon=Texture'ScrnAch_T.Maps.Swamp_2')
     AchDefs(139)=(id="KF-SwampHoE",DisplayName="Hellish Swamp",Description="Swamp",Icon=Texture'ScrnAch_T.Maps.Swamp_3')

     AchDefs(140)=(id="KF-TheLongDarkRoad",DisplayName="Long, Dark Road",Description="Long Dark Road",Icon=Texture'ScrnAch_T.Maps.LongDarkRoad_0')
     AchDefs(141)=(id="KF-TheLongDarkRoadHard",DisplayName="Long, Hard Road",Description="Long Dark Road",Icon=Texture'ScrnAch_T.Maps.LongDarkRoad_1')
     AchDefs(142)=(id="KF-TheLongDarkRoadSui",DisplayName="Path of the Ahmed",Description="Long Dark Road",Icon=Texture'ScrnAch_T.Maps.LongDarkRoad_2')
     AchDefs(143)=(id="KF-TheLongDarkRoadHoE",DisplayName="Road to Hell",Description="Long Dark Road",Icon=Texture'ScrnAch_T.Maps.LongDarkRoad_3')

     AchDefs(144)=(id="KF-BigSunrise",DisplayName="iPLAY",Description="Big Sunrise",Icon=Texture'ScrnAch_T.Maps.BigSunrise_0')
     AchDefs(145)=(id="KF-BigSunriseHard",DisplayName="iROCK",Description="Big Sunrise",Icon=Texture'ScrnAch_T.Maps.BigSunrise_1')
     AchDefs(146)=(id="KF-BigSunriseSui",DisplayName="iDIE",Description="Big Sunrise",Icon=Texture'ScrnAch_T.Maps.BigSunrise_2')
     AchDefs(147)=(id="KF-BigSunriseHoE",DisplayName="iKILL",Description="Big Sunrise",Icon=Texture'ScrnAch_T.Maps.BigSunrise_3')

     AchDefs(148)=(id="KF-SantasRetreat",DisplayName="Rudolf in the Sky",Description="Santa's Retreat",Icon=Texture'ScrnAch_T.Maps.SantasPad_0')
     AchDefs(149)=(id="KF-SantasRetreatHard",DisplayName="I See Dead Reindeers",Description="Santa's Retreat",Icon=Texture'ScrnAch_T.Maps.SantasPad_1')
     AchDefs(150)=(id="KF-SantasRetreatSui",DisplayName="Rudolf the Suicide Reindeer",Description="Santa's Retreat",Icon=Texture'ScrnAch_T.Maps.SantasPad_2')
     AchDefs(151)=(id="KF-SantasRetreatHoE",DisplayName="Sending Deer to Hell",Description="Santa's Retreat",Icon=Texture'ScrnAch_T.Maps.SantasPad_3')

     AchDefs(152)=(id="KF-ZedDisco",DisplayName="Backing Dancer",Description="ZED Disco",Icon=Texture'ScrnAch_T.Maps.ZedDisco_0')
     AchDefs(153)=(id="KF-ZedDiscoHard",DisplayName="DJ Skully",Description="ZED Disco",Icon=Texture'ScrnAch_T.Maps.ZedDisco_1')
     AchDefs(154)=(id="KF-ZedDiscoSui",DisplayName="King of the Dance Floor",Description="ZED Disco",Icon=Texture'ScrnAch_T.Maps.ZedDisco_2')
     AchDefs(155)=(id="KF-ZedDiscoHoE",DisplayName="Devil Dance",Description="ZED Disco",Icon=Texture'ScrnAch_T.Maps.ZedDisco_3')

     AchDefs(156)=(id="KF-CountyJail",DisplayName="Drunken Farmer Jail",Description="County Jail",Icon=Texture'ScrnAch_T.Maps.CountyJail_0')
     AchDefs(157)=(id="KF-CountyJailHard",DisplayName="Maximum Security Prison",Description="County Jail",Icon=Texture'ScrnAch_T.Maps.CountyJail_1')
     AchDefs(158)=(id="KF-CountyJailSui",DisplayName="Death Row",Description="County Jail",Icon=Texture'ScrnAch_T.Maps.CountyJail_2')
     AchDefs(159)=(id="KF-CountyJailHoE",DisplayName="Prison Break",Description="County Jail",Icon=Texture'ScrnAch_T.Maps.CountyJail_3')

     AchDefs(160)=(id="KF-Steamland",DisplayName="Astro Buffer Afficiando",Description="Steamland",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_209')
     AchDefs(161)=(id="KF-SteamlandHard",DisplayName="Modified Psychoacceleration Achiever",Description="Steamland",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_210')
     AchDefs(162)=(id="KF-SteamlandSui",DisplayName="Fractional Neutron Activator",Description="Steamland",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_211')
     AchDefs(163)=(id="KF-SteamlandHoe",DisplayName="Advanced Omega Wave Resonance Explorer",Description="Steamland",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_212')

     AchDefs(164)=(id="KF-FrightYard",DisplayName="Longshorman",Description="Fright Yard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_228')
     AchDefs(165)=(id="KF-FrightYardHard",DisplayName="Gang Crew",Description="Fright Yard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_229')
     AchDefs(166)=(id="KF-FrightYardSui",DisplayName="Stevedore",Description="Fright Yard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_230')
     AchDefs(167)=(id="KF-FrightYardHoe",DisplayName="Wharfinger",Description="Fright Yard",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_231')

     AchDefs(168)=(id="KF-Forgotten",DisplayName="Brain Fart",Description="Forgotten",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_247')
     AchDefs(169)=(id="KF-ForgottenHard",DisplayName="Agnosia",Description="Forgotten",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_248')
     AchDefs(170)=(id="KF-ForgottenSui",DisplayName="Amnesia",Description="Forgotten",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_249')
     AchDefs(171)=(id="KF-ForgottenHoe",DisplayName="Dementia",Description="Forgotten",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_250')

     AchDefs(172)=(id="KF-SirensBelch",DisplayName="Home Brewer",Description="Siren's Belch",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_252')
     AchDefs(173)=(id="KF-SirensBelchHard",DisplayName="Micro Brewer",Description="Siren's Belch",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_253')
     AchDefs(174)=(id="KF-SirensBelchSui",DisplayName="Master Brewer",Description="Siren's Belch",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_254')
     AchDefs(175)=(id="KF-SirensBelchHoe",DisplayName="Trappist Monk",Description="Siren's Belch",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_255')

     AchDefs(176)=(id="KF-Stronghold",DisplayName="Peasant",Description="Stronghold",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_256')
     AchDefs(177)=(id="KF-StrongholdHard",DisplayName="Squire",Description="Stronghold",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_257')
     AchDefs(178)=(id="KF-StrongholdSui",DisplayName="Prince",Description="Stronghold",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_258')
     AchDefs(179)=(id="KF-StrongholdHoe",DisplayName="King",Description="Stronghold",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_259')

     AchDefs(180)=(id="KF-Transit",DisplayName="Cattle Class",Description="Transit",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_260')
     AchDefs(181)=(id="KF-TransitHard",DisplayName="Economy Comfort",Description="Transit",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_261')
     AchDefs(182)=(id="KF-TransitSui",DisplayName="Business Class",Description="Transit",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_262')
     AchDefs(183)=(id="KF-TransitHoe",DisplayName="First Class",Description="Transit",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_263')

     AchDefs(184)=(id="KF-Clandestine",DisplayName="Gone clubbing",Description="Clandestine",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_275')
     AchDefs(185)=(id="KF-ClandestineHard",DisplayName="Rack 'em up",Description="Clandestine",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_276')
     AchDefs(186)=(id="KF-ClandestineSui",DisplayName="Burned out",Description="Clandestine",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_277')
     AchDefs(187)=(id="KF-ClandestineHoe",DisplayName="Hangover from Hell",Description="Clandestine",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_278')

     AchDefs(188)=(id="KF-ThrillsChills",DisplayName="Cave of Wonder",Description="Thrills Chills",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_280')
     AchDefs(189)=(id="KF-ThrillsChillsHard",DisplayName="Cavern of Pain",Description="Thrills Chills",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_281')
     AchDefs(190)=(id="KF-ThrillsChillsSui",DisplayName="Grotto of Terror",Description="Thrills Chills",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_282')
     AchDefs(191)=(id="KF-ThrillsChillsHoe",DisplayName="Hollow of Horror",Description="Thrills Chills",Icon=Texture'KillingFloor2HUD.Achievements.Achievement_283')

     AchDefs(192)=(id="KF-TheGreatPyramid-Arena",DisplayName="The First Encounter",Description="Great Pyramid",Icon=Texture'ScrnAch_T.Maps.Pyramid_0')
     AchDefs(193)=(id="KF-TheGreatPyramid-ArenaHard",DisplayName="The First Encounter: HD",Description="Great Pyramid",Icon=Texture'ScrnAch_T.Maps.Pyramid_1')
     AchDefs(194)=(id="KF-TheGreatPyramid-ArenaSui",DisplayName="Are You SERIOUS?",Description="Great Pyramid",Icon=Texture'ScrnAch_T.Maps.Pyramid_2')
     AchDefs(195)=(id="KF-TheGreatPyramid-ArenaHoe",DisplayName="Mental",Description="Great Pyramid",Icon=Texture'ScrnAch_T.Maps.Pyramid_3')

     AchDefs(196)=(id="KF-PandorasBox",DisplayName="Baby Box",Description="Pandora's Box",Icon=Texture'ScrnAch_T.Maps.Pandora_0')
     AchDefs(197)=(id="KF-PandorasBoxHard",DisplayName="Hard Box",Description="Pandora's Box",Icon=Texture'ScrnAch_T.Maps.Pandora_1')
     AchDefs(198)=(id="KF-PandorasBoxSui",DisplayName="Opening the Pandora's Box",Description="Pandora's Box",Icon=Texture'ScrnAch_T.Maps.Pandora_2')
     AchDefs(199)=(id="KF-PandorasBoxHoe",DisplayName="Unleashing Evil into Devil",Description="Pandora's Box",Icon=Texture'ScrnAch_T.Maps.Pandora_3')

     AchDefs(200)=(id="KF-ScrapHeap",DisplayName="Scrap Metal Merchant",Description="Scrap Heap",Icon=Texture'ScrnAch_T.Maps.ScrapHeap_0')
     AchDefs(201)=(id="KF-ScrapHeapHard",DisplayName="Underground Boxer",Description="Scrap Heap",Icon=Texture'ScrnAch_T.Maps.ScrapHeap_1')
     AchDefs(202)=(id="KF-ScrapHeapSui",DisplayName="King of the Box Ring",Description="Scrap Heap",Icon=Texture'ScrnAch_T.Maps.ScrapHeap_2')
     AchDefs(203)=(id="KF-ScrapHeapHoe",DisplayName="Knocking Down the Satan",Description="Scrap Heap",Icon=Texture'ScrnAch_T.Maps.ScrapHeap_3')

     AchDefs(204)=(id="KF-Train",DisplayName="Choo-Choo Train",Description="Train",Icon=Texture'ScrnAch_T.Maps.Train_0')
     AchDefs(205)=(id="KF-TrainHard",DisplayName="Poo-Poo Train",Description="Train",Icon=Texture'ScrnAch_T.Maps.Train_1')
     AchDefs(206)=(id="KF-TrainSui",DisplayName="Suicidal Train Driver",Description="Train",Icon=Texture'ScrnAch_T.Maps.Train_2')
     AchDefs(207)=(id="KF-TrainHoe",DisplayName="Baron of Hell",Description="Train",Icon=Texture'ScrnAch_T.Maps.Train_3')

     AchDefs(208)=(id="KF-WickedCity",DisplayName="Homeless resident of Wicked City",Description="Wicked City",Icon=Texture'ScrnAch_T.Maps.WickedCity_0')
     AchDefs(209)=(id="KF-WickedCityHard",DisplayName="Citizen of Wicked City",Description="Wicked City",Icon=Texture'ScrnAch_T.Maps.WickedCity_1')
     AchDefs(210)=(id="KF-WickedCitySui",DisplayName="Wicked City's First Maniac",Description="Wicked City",Icon=Texture'ScrnAch_T.Maps.WickedCity_2')
     AchDefs(211)=(id="KF-WickedCityHoe",DisplayName="Wicked Hell",Description="Wicked City",Icon=Texture'ScrnAch_T.Maps.WickedCity_3')

     AchDefs(212)=(id="KF-NightAngkor-SE",DisplayName="Entering Ancient Ruins",Description="Night Angkor",Icon=Texture'ScrnAch_T.Maps.NightAngkor_0')
     AchDefs(213)=(id="KF-NightAngkor-SEHard",DisplayName="Hardcore Anthropologist",Description="Night Angkor",Icon=Texture'ScrnAch_T.Maps.NightAngkor_1')
     AchDefs(214)=(id="KF-NightAngkor-SESui",DisplayName="Trampoline Jumper",Description="Night Angkor",Icon=Texture'ScrnAch_T.Maps.NightAngkor_2')
     AchDefs(215)=(id="KF-NightAngkor-SEHoe",DisplayName="Demon's Paradise",Description="Night Angkor",Icon=Texture'ScrnAch_T.Maps.NightAngkor_3')
}
